=== adriangargom/School_Portfolio/School Portfolio/M04/UF1/Practice 2/JJOO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="JJOO">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="edicio" type="xs:integer"/>

                <xs:element name="localitzacio">
                    <xs:complexType>
                        <xs:attribute name="pais" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="web">
                    <xs:complexType>
                        <xs:attribute name="url" type="xs:string"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="num_participants">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="countries" type="xs:integer"/>
                            <xs:element name="athletes" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="interest_dates">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="open_date" type="dateES"/>
                            <xs:element name="close_date" type="dateES"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                    
                <xs:element name="seusOnEsDisputenLesCompeticion">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="seu" maxOccurs="unbounded">
                                <xs:complexType>

                                    <xs:attribute name="nom" type="xs:string"/>
                                    <xs:attribute name="ciutat" type="xs:string"/>
                                    <xs:attribute name="edifici" type="xs:string"/>
                                    <xs:attribute name="funcionalitat" type="xs:string"/>

                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="sedesDondeSeDisputaronLasCompeticiones">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="seu" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="nomSeu">

                                            <xs:complexType>
                                                <xs:attribute name="nom" type="xs:string"/>
                                            </xs:complexType>   

                                        </xs:element>

                                        <xs:element name="ciutatSeu">

                                            <xs:complexType>
                                                <xs:attribute name="ciutat" type="xs:string"/>
                                            </xs:complexType>   

                                        </xs:element>

                                        <xs:element name="capacitatSeu">

                                            <xs:complexType>
                                                <xs:attribute name="capacitat" type="capacity"/>
                                            </xs:complexType>   

                                        </xs:element>

                                        <xs:element name="esportsAcollits">
                                            <xs:complexType>
                                                <xs:sequence>

                                                    <xs:element name="esport">
                                                        <xs:complexType>
                                                            <xs:sequence>

                                                                <xs:element name="categoriaEsport" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>

                                                                            <xs:element name="medalles">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>

                                                                                        <xs:element name="Categoria" maxOccurs="unbounded">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>

                                                                                                    <xs:element name="paisGuanyador">
                                                                                                        <xs:complexType>
                                                                                                            <xs:attribute name="pais" type="xs:string"/>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>

                                                                                                    <xs:element name="atletaGuanyador">
                                                                                                        <xs:complexType>
                                                                                                            <xs:attribute name="atleta" type="xs:string"/>
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>

                                                                                                <xs:attribute name="tipusMedalla" type="medals"/>
                                                                                                <xs:attribute name="diaGuanyada" type="dateES"/>
                                                                                                <xs:attribute name="horaDeComencament" type="hour"/>
                                                                                                <xs:attribute name="dinsDeLaSeuLlocDeDisputa" type="xs:string"/>

                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>

                                                                        <xs:attribute name="nom" type="xs:string"/>
                                                                        <xs:attribute name="sexe" type="gender"/>

                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>

                                                            <xs:attribute name="nom" type="xs:string"/>
                                                            <xs:attribute name="anyPrimerCopEsportOlimpic" type="any"/>
                                                            <xs:attribute name="dataInici" type="dateES"/>
                                                            <xs:attribute name="dataFinalizacio" type="dateES"/>

                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                
                                                <xs:attribute name="esportsAcollitsALaSeu" type="xs:string"/>
                                            
                                            </xs:complexType>
                                        </xs:element>   

                                    </xs:sequence>

                                    <xs:attribute name="esportDisputat" type="xs:string"/>
                                
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <xs:attribute name="identificador" type="xs:string"/>
        
        </xs:complexType>
    </xs:element>





    <!-- Restrinctions -->

    <!-- Date format restrinction -->
    <xs:simpleType name="dateES">
        <xs:restriction base="xs:string">

            <xs:pattern value="[0-9]{2}/[0-9]{2}/[0-9]{4}"/>

        </xs:restriction>
    </xs:simpleType>
    
    <!-- Hour format Restrinction -->
    <xs:simpleType name="hour">
        <xs:restriction base="xs:string">

            <xs:pattern value="[0-9][0-9]:[0-9][0-9]"/>

        </xs:restriction>
    </xs:simpleType>

    <!-- Medal Type Restriction -->
    <xs:simpleType name="medals">
        <xs:restriction base="xs:string">

            <xs:enumeration value="or"/>
            <xs:enumeration value="plata"/>
            <xs:enumeration value="bronze"/>

        </xs:restriction>
    </xs:simpleType>

    <!-- Gender Restrinction -->
    <xs:simpleType name="gender">
        <xs:restriction base="xs:string">

            <xs:enumeration value="masculi"/>
            <xs:enumeration value="femeni"/>
            <xs:enumeration value="masculi, femeni"/>

        </xs:restriction>
    </xs:simpleType>

    <!-- Capacity Restrinction -->
    <xs:simpleType name="capacity">
        <xs:restriction base="xs:string">

            <xs:pattern value="[0-9]{3,6} - [0-9]{3,6}"/>

        </xs:restriction>
    </xs:simpleType>

    <!-- Any primer cop esport Olimpic restrinction -->
    <xs:simpleType name="any">
        <xs:restriction base="xs:integer">

            <xs:minInclusive value="1000"/>
            <xs:maxInclusive value="10000"/>

        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== adriangargom/School_Portfolio/M04/UF1/Practice 2/JJOO.xml
<?xml version= "1.0" encoding= "UTF-8"?>

<JJOO identificador="Tokio 2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JJOO.xsd">

    <edicio>32</edicio>
    <localitzacio pais="Tokio, Japon"/>
    <web url="https://olympics.com/es/olympic-games/tokyo-2020"/>

    <num_participants>
        <countries>205</countries>
        <athletes>11420</athletes>
    </num_participants>
    
    <interest_dates>
        <open_date>27/07/2020</open_date>
        <close_date>08/08/2020</close_date>
    </interest_dates>

    <seusOnEsDisputenLesCompeticion>

        <seu nom="Seu de ceremonia d'apertura" ciutat="Tokio Japón" edifici="Estadio Olímpico de Tokio" funcionalitat="Ceremonia apertura Jocs Olimpics"/>
        <seu nom="Seu de ceremonia clausura" ciutat="Tokio Japón" edifici="Estadio Olímpico de Tokio" funcionalitat="Ceremonia clausura Jocs Olimpics"/>
        <seu nom="Seu de COI" ciutat="Suiza Lausana" edifici="sede central del Comité Olímpico Internacional" funcionalitat="Coordinar las actividades del Movimiento Olímpico"/>
        <seu nom="Villa Olimpica" ciutat="Tokio Chuo Ward" edifici="Chuo Ward" funcionalitat="Acollir a atletes y personal dels jocs Olimpics"/>
        <seu nom="Centres de medis" ciutat="Tokio Chuo Ward" edifici="Tokio Big Sight" funcionalitat="Administrar els medis de comunicacio"/>
        <seu nom="Centre internacional de prensa" ciutat="Tokio Chuo Ward" edifici="Tokio Big Sight" funcionalitat="Administrar a la prensa"/>

    </seusOnEsDisputenLesCompeticion>

    <!-- Seus on es van disputar les competicions -->
    <sedesDondeSeDisputaronLasCompeticiones>

        <!--Seu de l'Esport 1. Basquet-->
        <seu esportDisputat="Basquet">

            <nomSeu nom="Saitama Super Arena"/>
            <ciutatSeu ciutat="Chūō-ku, Saitama"/>
            <capacitatSeu capacitat="19000 - 22500"/>
            
            <!-- Esports Acollits dins de la seu -->
            <esportsAcollits esportsAcollitsALaSeu="Boxeo, basquet, volley, tenis, hockey sobre hielo, gimnasia">

                <!-- Esport 1 acollit a la seu - Basquet -->
                <esport nom="Basquet 5x5" anyPrimerCopEsportOlimpic="1904" dataInici="25/07/2020" dataFinalizacio="08/09/2020">
                    
                    <!-- Categoria Numero 1 -->
                    <categoriaEsport nom="5x5" sexe="masculi, femeni">

                        <medalles>
                            <!-- Medalla de Or -->
                            <Categoria tipusMedalla="or" diaGuanyada="07/08/2020" horaDeComencament="03:30" dinsDeLaSeuLlocDeDisputa="Saitama Super Arena">
                                <paisGuanyador pais="Estados Unidos"/>
                                <atletaGuanyador atleta="Estados Unidos"/>
                            </Categoria>
                            <!-- Medalla de Plata -->
                            <Categoria tipusMedalla="plata" diaGuanyada="07/08/2020" horaDeComencament="03:30" dinsDeLaSeuLlocDeDisputa="Saitama Super Arena">
                                <paisGuanyador pais="Francia"/>
                                <atletaGuanyador atleta="Estados Unidos"/>
                            </Categoria>
                            <!-- Medalla de Bronze -->
                            <Categoria tipusMedalla="bronze" diaGuanyada="07/08/2020" horaDeComencament="03:30" dinsDeLaSeuLlocDeDisputa="Saitama Super Arena">
                                <paisGuanyador pais="Australia"/>
                                <atletaGuanyador atleta="Estados Unidos"/>

                            </Categoria>

                        </medalles>

                    </categoriaEsport>

                    <!-- Categoria Numero 2 -->
                    <categoriaEsport nom="Basquet 3x3" sexe="masculi, femeni">

                        <medalles>
                            <!-- Medalla de Or -->
                            <Categoria tipusMedalla="or" diaGuanyada="07/07/2020" horaDeComencament="15:25" dinsDeLaSeuLlocDeDisputa="Saitama Super Arena">
                                <paisGuanyador pais="Letonia"/>
                                <atletaGuanyador atleta="Letonia"/>
                            </Categoria>
                            <!-- Medalla de Plata -->
                            <Categoria tipusMedalla="plata" diaGuanyada="07/07/2020" horaDeComencament="15:25" dinsDeLaSeuLlocDeDisputa="Saitama Super Arena">
                                <paisGuanyador pais="ROC"/>
                                <atletaGuanyador atleta="ROC"/>
                            </Categoria>
                            <!-- Medalla de Bronze -->
                            <Categoria tipusMedalla="bronze" diaGuanyada="07/07/2020" horaDeComencament="15:25" dinsDeLaSeuLlocDeDisputa="Saitama Super Arena">
                                <paisGuanyador pais="Serbia"/>
                                <atletaGuanyador atleta="Serbia"/>
                            </Categoria>

                        </medalles>
                    </categoriaEsport>
                </esport>
            </esportsAcollits>
        </seu>

        <!--Seu de l'Esport 2. SkateBoarding-->
        <seu esportDisputat="SkateBoarding">

            <nomSeu nom="Parque Deportivo Urbano de Ariake"/>
            <ciutatSeu ciutat="Ariake"/>
            <capacitatSeu capacitat="6000 - 7000"/>
            
            <!-- Esports Acollits dins de la seu -->
            <esportsAcollits esportsAcollitsALaSeu="skateboarding y ciclismo olimpico">

                <!-- Esport 1 acollit a la seu - Basquet -->
                <esport nom="SkateBoarding" anyPrimerCopEsportOlimpic="1994" dataInici="24/07/2020" dataFinalizacio="25/07/2020">
                    
                    <!-- Categoria Numero 1 -->
                    <categoriaEsport nom="Carrer" sexe="masculi, femeni">

                        <medalles>
                            <!-- Medalla de Or -->
                            <Categoria tipusMedalla="or" diaGuanyada="25/07/2020" horaDeComencament="02:00" dinsDeLaSeuLlocDeDisputa="Skatepark">
                                <paisGuanyador pais="Japon"/>
                                <atletaGuanyador atleta="Yuto Horigome"/>
                            </Categoria>
                            <!-- Medalla de Plata -->
                            <Categoria tipusMedalla="plata" diaGuanyada="25/07/2020" horaDeComencament="02:00" dinsDeLaSeuLlocDeDisputa="Skatepark">
                                <paisGuanyador pais="Brazil"/>
                                <atletaGuanyador atleta=" Kelvin Hoefler"/>
                            </Categoria>
                            <!-- Medalla de Bronze -->
                            <Categoria tipusMedalla="bronze" diaGuanyada="25/07/2020" horaDeComencament="02:00" dinsDeLaSeuLlocDeDisputa="Skatepark">
                                <paisGuanyador pais="Estados Unidos"/>
                                <atletaGuanyador atleta="Jagger Eaton"/>
                            </Categoria>
                        </medalles>

                    </categoriaEsport>

                    <!-- Categoria Numero 2 -->
                    <categoriaEsport nom="Parc" sexe="masculi, femeni">

                        <medalles>
                            <!-- Medalla de Or -->
                            <Categoria tipusMedalla="or" diaGuanyada="05/08/2020" horaDeComencament="02:00" dinsDeLaSeuLlocDeDisputa="Skatepark">
                                <paisGuanyador pais="Australia"/>
                                <atletaGuanyador atleta="Keegan Palmer"/>
                            </Categoria>
                            <!-- Medalla de Plata -->
                            <Categoria tipusMedalla="plata" diaGuanyada="05/08/2020" horaDeComencament="02:00" dinsDeLaSeuLlocDeDisputa="Skatepark">
                                <paisGuanyador pais="Brazil"/>
                                <atletaGuanyador atleta="Pedro Barros"/>
                            </Categoria>
                            <!-- Medalla de Bronze -->
                            <Categoria tipusMedalla="bronze" diaGuanyada="05/08/2020" horaDeComencament="02:00" dinsDeLaSeuLlocDeDisputa="Skatepark">
                                <paisGuanyador pais="Estados Unidos"/>
                                <atletaGuanyador atleta="Cory Juneau"/>
                            </Categoria>

                        </medalles>
                    </categoriaEsport>
                </esport>
            </esportsAcollits>
        </seu>

        <!--Seu de l'Esport 3. Tenis de Taula-->
        <seu esportDisputat="Ciclisme Olimpic">

            <nomSeu nom="Parque Deportivo Urbano de Ariake"/>
            <ciutatSeu ciutat="Ariake"/>
            <capacitatSeu capacitat="5000 - 6000"/>
            
            <!-- Esports Acollits dins de la seu -->
            <esportsAcollits esportsAcollitsALaSeu="skateboarding y ciclismo olimpico">

                <!-- Esport 1 acollit a la seu - Basquet -->
                <esport nom="Ciclisme" anyPrimerCopEsportOlimpic="1896"  dataInici="25/06/2020" dataFinalizacio="05/08/2020">
                    
                    <!-- Categoria Numero .1 - de BMX Freestyle-->
                    <categoriaEsport nom="BMX Freestyle" sexe="masculi, femeni">

                        <!-- Medalles -->
                        <medalles>
                            <!-- Medalla de Or -->
                            <Categoria tipusMedalla="or" diaGuanyada="01/08/2020" horaDeComencament="03:10" dinsDeLaSeuLlocDeDisputa="La Pista">
                                <paisGuanyador pais="Australia"/>
                                <atletaGuanyador atleta="Logan Martin"/>
                            </Categoria>
